### ISSUE TITLE
[bug] attempt to call field 'deep_copy' (a nil value)

### ISSUE THREAD

**Issue by strash** [j-morano/buffer_manager.nvim#15] opened 2023-02-17 14:35 UTC
I'm getting this error when trying to close the buffer_manager popup window. 

```lua
E5108: Error executing lua ...cker/start/buffer_manager.nvim/lua/buffer_manager/ui.lua:340: attempt to call field 'deep_copy' (a nil value)
stack traceback:
        ...cker/start/buffer_manager.nvim/lua/buffer_manager/ui.lua:340: in function 'set_mark_list'
        ...cker/start/buffer_manager.nvim/lua/buffer_manager/ui.lua:363: in function 'on_menu_save'
        ...cker/start/buffer_manager.nvim/lua/buffer_manager/ui.lua:316: in function 'select_menu_item'
        [string ":lua"]:1: in main chunk
```

**Comment by j-morano** [comment] 2023-02-17 18:57
Hello. I cannot reproduce. How is your config for the plugin? And how do you close the window when you get the error? Or do you always get it?

**Comment by strash** [comment] 2023-02-17 20:01
Hi. I couldn't close the window and just closed neovim. And after that I can't reproduce this bug anymore. It happens once, so I don't know what is the cause.

My config:
```lua
use({
	"j-morano/buffer_manager.nvim",
	requires = "nvim-lua/plenary.nvim",
	config = function()
		require("buffer_manager").setup({
			width = 100,
			height = 12,
			focus_alternate_buffer = true,
		})
	end
})
```

**Comment by j-morano** [comment] 2023-02-27 17:43
Did it happen again to you? I cannot reproduce.

**Comment by strash** [comment] 2023-02-27 17:56
No

**Comment by j-morano** [comment] 2023-02-27 18:22
Okay. Thus, if you do not mind, I will close the issue. Feel free to open it again if the problem appears again. Thanks anyway for the feedback!

**Closed** 2023-02-28 08:48 UTC
Labels: bug
