### ISSUE TITLE
Feature: Reorganize Buffers

### ISSUE THREAD

**Issue by DennisTheMenace780** [j-morano/buffer_manager.nvim#3] opened 2022-11-27 02:58 UTC
Currently the Buffer UI does not allow for ordering buffers. It would be great if we could reorder buffers, such as the example below:

Non-Ordered
```lua
1. . 
2. important_file_2
3. important_file_3
4. important_file_1
```

Ordered
```lua
1. .
2. important_file_1
3. important_file_2
4. important_file_3
``` 

By reordering the buffers we're able to associate the most important files with keystrokes. A more concrete example of this would be if you had several buffers open, and you wanted the last several buffers to always be your file that contains tests.

**Comment by j-morano** [comment] 2022-11-27 11:20
Hi! Thanks for the feedback. I found the idea very interesting, and I have been working on it. As it has required some important changes in `ui.lua`, I have uploaded the version with this feature to the branch `reorganize-buffers` (see 1d0c1e9). Would you be willing to test it thoroughly before merging the changes to the `main` branch?
If you use `packer.nvim`, you can change the branch this way:
```lua
  use { 'j-morano/buffer_manager.nvim', branch = 'reorganize-buffers' }
```
I will close the issue once it is confirmed that it really works as it should.

**Comment by DennisTheMenace780** [comment] 2022-11-27 19:23
Yup! Can give it a go today and see if if anything weird pops out.

**Comment by j-morano** [comment] 2022-11-29 22:22
First version had some bugs. I have added a few commits to solve them.

**Comment by DennisTheMenace780** [comment] 2022-11-30 16:12
I've done some playing around with it and I think it works as expected! The UX of moving things around can probably be enhanced at some point, but that's really a small detail. 

Right now I can enter new lines in the buffer, cut-paste the buffers in the order that I want and that works as expected! Thanks for your effort.

**Comment by j-morano** [comment] 2022-11-30 17:37
You are welcome!
Regarding the UX, I personally do not have the need for changing it, but mostly because I use the following remaps:
```lua
local map = vim.keymap.set
opts = {noremap = true}
map('v', 'J', ":m '>+1<CR>gv=gv", opts)
map('v', 'K', ":m '<-2<CR>gv=gv", opts)
```
With this remaps, you can move a line up and down with capital K and J, respectively.
It is true that if you do not have some remaps like these moving buffers is not so straightforward.

Related to this, here goes an useful trick: since the menu is just a buffer, you can define your own remaps using an autocmd for the file type `buffer_manager`. For example:
```vim
autocmd FileType buffer_manager vnoremap J :m '>+1<CR>gv=gv
autocmd FileType buffer_manager vnoremap J :m '<-2<CR>gv=gv
```

Finally, thanks for the feedback. Although everything seems to be going well, I will try this branch for a while before merging it with main.

**Comment by DennisTheMenace780** [comment] 2022-11-30 20:04
Sounds great to me! I might those keybinds out then because that would immediately solve the UX problem.

**Comment by j-morano** [comment] 2022-12-04 11:59
I have just merged `reorganize-buffers` branch with `main`. I think it works fine, so I am closing this issue. Feel free to open another issue if something does not work as expected.

**Closed by j-morano** 2022-12-04 11:59 UTC
Labels: feature
